"""
Generate precomputed Mel Filterbank, Hann Window, and DCT tables for ESP32 firmware.

Matches the Python training pipeline:
  Librosa MFCC: sr=16000, n_fft=512, hop_length=256, n_mels=40, n_mfcc=13
  fmin=0.0, fmax=8000.0, htk=False, norm='slaney'
  Hann window: fftbins=True (periodic, 512 samples)
  DCT-II: ortho, 13 x 40
"""

import argparse
from pathlib import Path
import numpy as np
import librosa
import scipy.fftpack

SAMPLE_RATE = 16000
FFT_SIZE = 512
N_MELS = 40
N_MFCC = 13
FMIN = 0.0
FMAX = 8000.0


def generate_tables(output_path: Path):
    # 1. Hann Window (periodic / fftbins=True matching Librosa STFT)
    hann = librosa.filters.get_window("hann", FFT_SIZE, fftbins=True).astype(np.float32)

    # 2. Mel Filterbank (Slaney-normalized triangular filters)
    mel_basis = librosa.filters.mel(
        sr=SAMPLE_RATE,
        n_fft=FFT_SIZE,
        n_mels=N_MELS,
        fmin=FMIN,
        fmax=FMAX,
        htk=False,
        norm="slaney",
    ).astype(np.float32)

    # Convert Mel basis to sparse filters
    sparse_filters = []
    sparse_weights = []
    current_offset = 0

    for m in range(N_MELS):
        row = mel_basis[m]
        nonzero_indices = np.where(row > 0)[0]
        if len(nonzero_indices) == 0:
            start_bin = 0
            count = 0
        else:
            start_bin = int(nonzero_indices[0])
            end_bin = int(nonzero_indices[-1])
            count = end_bin - start_bin + 1

        sparse_filters.append({
            "start_bin": start_bin,
            "num_weights": count,
            "weight_offset": current_offset,
        })
        weights = row[start_bin : start_bin + count]
        sparse_weights.extend(weights.tolist())
        current_offset += count

    total_sparse_weights = len(sparse_weights)

    # 3. DCT-II Ortho Matrix (13 x 40)
    dct_mat = scipy.fftpack.dct(np.eye(N_MELS), type=2, norm="ortho", axis=0)[:N_MFCC].astype(np.float32)

    # Generate C header content
    lines = [
        "/**",
        " * @file mel_tables.h",
        " * @brief Precomputed tables for 40-Mel MFCC feature extraction on ESP32",
        " *",
        " * Auto-generated by tools/generate_mel_tables.py",
        " * Matches Librosa:",
        f" *   sr={SAMPLE_RATE}, n_fft={FFT_SIZE}, n_mels={N_MELS}, n_mfcc={N_MFCC}",
        " *   fmin=0.0, fmax=8000.0, htk=False, norm='slaney'",
        " */",
        "",
        "#ifndef MEL_TABLES_H_",
        "#define MEL_TABLES_H_",
        "",
        "#include <stdint.h>",
        "",
        f"#define MEL_TOTAL_SPARSE_WEIGHTS {total_sparse_weights}",
        "",
        f"static const float s_hann_window[{FFT_SIZE}] = {{",
    ]

    # Format Hann window (8 floats per line)
    for i in range(0, FFT_SIZE, 8):
        chunk = hann[i : i + 8]
        vals = ", ".join(f"{v:.8e}f" for v in chunk)
        lines.append(f"    {vals},")
    lines.append("};\n")

    # Format Filter struct
    lines.extend([
        "typedef struct {",
        "    int16_t start_bin;",
        "    int16_t num_weights;",
        "    int16_t weight_offset;",
        "} mel_sparse_filter_t;",
        "",
        f"static const mel_sparse_filter_t s_filters[{N_MELS}] = {{",
    ])
    for f in sparse_filters:
        lines.append(f"    {{ {f['start_bin']}, {f['num_weights']}, {f['weight_offset']} }},")
    lines.append("};\n")

    # Format Sparse weights (8 floats per line)
    lines.append(f"static const float s_mel_weights[{total_sparse_weights}] = {{")
    for i in range(0, total_sparse_weights, 8):
        chunk = sparse_weights[i : i + 8]
        vals = ", ".join(f"{v:.8e}f" for v in chunk)
        lines.append(f"    {vals},")
    lines.append("};\n")

    # Format DCT Matrix (8 floats per line)
    dct_flat = dct_mat.flatten()
    lines.append(f"static const float s_dct_matrix[{N_MFCC} * {N_MELS}] = {{")
    for i in range(0, len(dct_flat), 8):
        chunk = dct_flat[i : i + 8]
        vals = ", ".join(f"{v:.8e}f" for v in chunk)
        lines.append(f"    {vals},")
    lines.append("};\n")

    lines.append("#endif /* MEL_TABLES_H_ */\n")

    content = "\n".join(lines)
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Generated {output_path}")
    print(f"  Hann samples:        {FFT_SIZE}")
    print(f"  Mel filters:         {N_MELS}")
    print(f"  Total sparse weights:{total_sparse_weights}")
    print(f"  DCT matrix size:     {N_MFCC} x {N_MELS} ({len(dct_flat)} floats)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate mel_tables.h")
    parser.add_argument(
        "--out",
        type=str,
        default=str(Path(__file__).resolve().parent.parent / "main" / "mel_tables.h"),
    )
    args = parser.parse_args()
    generate_tables(Path(args.out))
